DATA:
#    ROOT: '/home/fengchuang/TimeSformer-main/KoNViD_1k_videos'
#    TRAIN_FILE: '/home/fengchuang/TimeSformer-main/dataset_csv/kon1kcsv/train.csv'
#    VAL_FILE: '/home/fengchuang/TimeSformer-main/dataset_csv/kon1kcsv/test.csv'
#    ROOT: '/home/fengchuang/TimeSformer-main/CNN_features_VQC-585'
#    TRAIN_FILE: '/home/fengchuang/TimeSformer-main/dataset_csv/vqccsv/train.csv'      ######100
#    VAL_FILE: '/home/fengchuang/TimeSformer-main/dataset_csv/vqccsv/test.csv'
    ROOT: '/home/fengchuang/zax/LSVQ'
    TRAIN_FILE: '/home/fengchuang/TimeSformer-main/dataset_csv/LSVQcsv/LSVQ1080/train.csv'   ####100
    VAL_FILE: '/home/fengchuang/TimeSformer-main/dataset_csv/LSVQcsv/LSVQ1080/test.csv'
    DATASET: kinetics400
    NUM_FRAMES: 8
    NUM_CLASSES: 6
    LABEL_LIST: '/home/fengchuang/VideoX-master/X-CLIP/labels/kinetics_400_labels.csv'
MODEL:
    ARCH: ViT-L/14
#    RESUME: '/home/fengchuang/VideoX-master/X-CLIP/exp/k400_14_8.pth'
#    RESUME: '/home/fengchuang/VideoX-1/X-CLIP/exp/ckpt_epoch_26.pth'
TRAIN:
    BATCH_SIZE: 1
    ACCUMULATION_STEPS: 8
